## CIND830 - Python Programming for Data Science  
### Assignment 2 (10% of the final grade)
### Due on November 15, 2021 11:59 PM

*****
This is a Jupyter Notebook document that extends a simple formatting syntax for authoring HTML and PDF.
Review [this](https://jupyter-notebook.readthedocs.io/en/stable/notebook.html) website for more details on using Juputer Notebook.

Use the JupyterHub server on the Google Cloud Platform,
provided by your designated instructor, for this assignment.
Complete the assignment by inserting your Python code wherever you see the string
"#INSERT YOUR ANSWER HERE."

When you click the `File` button, from the top navigation bar, then select `Export Notebook As ...`,
a document (PDF or HTML format) will be generated that includes
 both the assignment content and the output of any embedded Python code chunks.

Using [these](https://www.ryerson.ca/courses/students/tutorials/assignments/) guidelines,
submit **both** the IPYNB and the exported file (PDF or HTML).
Failing to submit both files will be subject to mark deduction.

*****

### Question 1 **[30 pts]**:

**a)** **[5 pts]** Define a function called `is_symmetrical` that takes a string value as a parameter and returns `True` if the given string is Symmetrical. A string is said to be symmetrical if the reverse of the string is the same as string. For example, “madam” is symmetrical, but “water” is not symmetrical. Note that strings are case sensitive.

In [137]:
def is_symmetrical(mystring):
    newstring = ""
    for i in range(len(mystring) - 1, -1, -1):
        newstring = newstring + mystring[i]
    if newstring == mystring:
        result = True
    else:
        result = False
    return result
is_symmetrical("madam")


True

**b)** **[5 pts]** Modify the `is_symmetrical` function you created in Q1.a to take any data type (int,str,etc.) as an input and return `True` if the input is symmetrical. For example, "12321" is symmetrical, but "12345" is not symmetrical.

In [136]:
myinputnum = 12345
myinputstring = "123321"
myinputfloat = 123.321

def is_symmetrical(myinput): #consider only integers, strings, and floating-point numbers based on TA's answer on discussion board
    if type(myinput) == int:
        newstring = int(str(myinput)[::-1])
    elif type(myinput) == float:
        newstring = float(str(myinput)[::-1])
    else: #string
        newstring = myinput[::-1]

    if newstring == myinput:
        result = True
    else:
        result = False
    return result
is_symmetrical(myinputstring)


True

**c)** **[5 pts]** Define a function called `is_symmetrical_vec` that calls `is_symmetrical` function you updated in Q1.b to take a list of elements and return their results in a list.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns \[`True`, `False`, `True`, `True`, `False`\]

In [132]:
samplelist = ["1441", "Apple", "radar", "232", "plane"]

def is_symmetrical_vec(mylist):
    resultlist = []
    for element in mylist:
        resultlist.append(is_symmetrical(element))
    return resultlist

is_symmetrical_vec(samplelist)

[True, False, True, True, False]

**d)** **[7 pts]** Define a function called `is_symmetrical_dict` by modifying the function you created in Q1.c to return the results in a dictionary with their corresponding input elements. \
For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns {"1441": `True`, "Apple": `False`, "radar": `True`, "232": `True`, "plane": `False`\}

In [131]:
samplelist = ["1441", "Apple", "radar", "232", "plane"]
def is_symmetrical_dict(mylist):
    resultdict = {}
    for element in mylist:
        resultdict[element] = is_symmetrical(element)
    return resultdict

is_symmetrical_dict(samplelist)


{'1441': True, 'Apple': False, 'radar': True, '232': True, 'plane': False}

**e)** **[8 pts]** Define a function called `is_symmetrical_tuple` by modifying the function you created in Q1.d to traverse the values of the returned dictionary **in reverse order** and return the dictionary keys that has a **`True`** value as a tuple.  For example, given \["1441", "Apple", "radar", "232", "plane"\] the function returns ("232", "radar","1441").

In [130]:
samplelist = ["1441", "Apple", "radar", "232", "plane"]
def is_symmetrical_dict(mylist):
    resultdict = {}
    keystuple = ()
    for element in mylist:
        resultdict[element] = is_symmetrical(element)
    for key, value in resultdict.items():
        if (value == True):
            keystuple = keystuple + (key,)
            keystuple = tuple(reversed(keystuple))
    return keystuple

is_symmetrical_dict(samplelist)


('232', '1441', 'radar')

*****



### Question 2 **[40 pts]** :
The data file used in this question is downloaded from https://www.kaggle.com/arjunprasadsarkhel/2021-olympics-in-tokyo and converted to a csv file.



**a)** **[15 pts]** The [`Medals.csv`](https://app.box.com/s/92u6ydp0zih0gygwr8xl77vy3x0prq0u) is a delimited text file containing the number of medals of teams in the 2021 Olympics in Tokyo. The file contains the following columns separated by the comma character `, `
*  Rank
*  Team/NOC
*  Gold
*  Silver
*  Bronze
*  Total
*  Rank by Total 

Write a code that asks the user to enter the file's name: `Medals.csv.`
 If the program finds the file in the folder in which you stored it, it will read the file's contents into a list of lists called `medalsList`.  Each list inside the `medalsList` represents one row from the `Medals.csv` file.  Ensure that your code reads and stores each row as a list of strings inside the `medalsList` data structure. For example the first row would be `['1', 'United States of America', '39', '41', '33', '113', '1']`

In [141]:
filename = input("Please enter the file's name.")
MedalsList = []
import csv
with open(r'C:/Users/Daria/Downloads/' + filename, newline='') as csvfile:
    has_header = csv.Sniffer().has_header(csvfile.read(1024))
    csvfile.seek(0)
    filereader = csv.reader(csvfile, delimiter=',', quotechar='|')
    if has_header:
        next(filereader)  # Skip header row.
    for row in filereader:
        MedalsList.append(row)
print(MedalsList[1])

Please enter the file's name.Medals.csv
['2', "People's Republic of China", '38', '32', '18', '88', '2']


**b)** **[15 pts]** Write a code that asks the user to enter a team name and medal type; then, it will display the total number of medals that the team has won. For example, if the user enters `Canada` as the team's name and `Gold` as the medal's type, the code should display `7`.

Make sure your code handles the following four issues:
1. The user is allowed to enter lowercase and uppercase letters; your code must be case insensitive (e.g. if the user enters `canADa`, it still needs to locate `Canada` correctly)
2. Your code should use the list `medalList` that you created in question Q2.a, rather than repeatedly reads the data from the `Medals.csv` file.
3. The user can enter either `Gold`, `Silver`, `Bronze` or `All` for the medal's type.   For example, if the user enters `Canada` and `All`, the code should display `Gold: 7, Silver: 6, Bronze: 11, Total: 24`.
4. If the user enters a team's name that is not in the list, the code should notify the user.  For example, if the user enters `Mozambique` as the team's name, the code would display: `Unfortunately, Mozambique did not participate in the 2021 Olympics!`


In [142]:
teamname = input("Please enter a team name.")
medaltype = input("Please enter a medal type.")
 
#Error Handling for case-sensitivity
newteamname = teamname.title()
notinlist = ""
for i in range(len(MedalsList)):
    if newteamname in MedalsList[i][1]:
        gold = "Gold: " + MedalsList[i][2]
        silver = "Silver: " + MedalsList[i][3]
        bronze = "Bronze: " + MedalsList[i][4]
        total = "Total: " + MedalsList[i][5]
        if medaltype == "Gold":
            print(gold)
            notinlist = "N"
        elif medaltype == "Silver":
            print(silver)
            notinlist = "N"
        elif medaltype == "Bronze":
            print(bronze)
            notinlist = "N"
        elif medaltype == "All":
            print(gold + "," + " " + silver + "," + " " + bronze + "," + " " + total)
            notinlist = "N"

if notinlist == "":
    print("Unfortunately, " + newteamname + " did not participate in the 2021 Olympics!")
    notinlist = "" #reset
        


Please enter a team name.canada
Please enter a medal type.All
Gold: 7, Silver: 6, Bronze: 11, Total: 24


**c)** **[10 pts]** Write a code that will ask the first letter of the team name and display the total of the medals (grouped by the medal type) taken by the teams starting with the first letter as the selected one. E.g. if the user enters `f` (case insensitive) as the first letter of the team, then your code will scan the list, find the teams `France`, `Fiji`, and `Finland` then it will display the total medals `Gold: 11, Silver: 12, Bronze: 14` (the total Gold medals of the teams starting with `f`, the total Silver of the  teams starting with `f`, etc.  
Make sure your code handle the cases listed below:

*   The user is allowed to enter lowercase and uppercase letter, your code must be case insensitive.
*   Your code must **use** (do not read the file again) the list created in question **Q2.a** containing all the information read from the file
*   If there is no team name starting with the selected letter then your code needs to display an error message like `No team name starts with your selected letter in the 2021 Olympics`  

In [143]:
teamletter = input("Please enter the first letter of the team name.")
teamslist = []
totalgold = totalsilver = totalbronze = totaltotal = 0
#Error Handling for case-sensitivity
teamletter = teamletter.upper()
for i in range(len(MedalsList)):
    if teamletter == MedalsList[i][1][0]:
        totalgold = totalgold + int(MedalsList[i][2])
        totalsilver = totalsilver + int(MedalsList[i][3])
        totalbronze = totalbronze + int(MedalsList[i][4])
        #totaltotal = totaltotal + int(MedalsList[i][5])
        
gold = "Gold: " + str(totalgold)
silver = "Silver: " + str(totalsilver)
bronze = "Bronze: " + str(totalbronze)
#total = "Total: " + str(totaltotal)
result = gold + "," + " " + silver + "," + " " + bronze# + "," + " " + total
teamslist.append(result)

if totalgold == 0 and totalsilver == 0 and totalbronze == 0: #if empty aka no results
    print("No team name starts with your selected letter in the 2021 Olympics!")
else:
    print(teamslist)

Please enter the first letter of the team name.f
['Gold: 11, Silver: 12, Bronze: 14']


*****

### Question 3 **[30 pts]** :
**a)** Define three classes: **Vehicle**, **Car** and **Truck**. Vehicle will be the parent class of Car and Truck.
- Randomly create five objects of Car and Truck using the for loop given below
- The program should output the correct number of vehicles: Car and Truck objects. 
- **The count of objects should be calculated within the class definitions**.
  - Example output \\
  There are  5  Vehicle objects ['Car', 'Car', 'Truck', 'Truck', 'Car'] \\
	 3 of them are Cars \\
	 2 of them are Trucks \\


In [144]:
from random import choice


class Vehicle:
    numVehicles = 0

    def __init__(self):
        Vehicle.numVehicles += 1


class Car(Vehicle):
    numCars = 0

    def __init__(self):
        Car.numCars += 1
        super().__init__()


class Truck(Vehicle):
    numTrucks = 0

    def __init__(self):
        global numTrucks
        Truck.numTrucks += 1
        super().__init__()


list_of_vehicles = [choice(['Car', 'Truck']) for x in range(5)]
for vehicle in list_of_vehicles:
    if vehicle == 'Car':
        o = Car()
    else:
        c = Truck()

result = "There are " + str(Vehicle.numVehicles) + " Vehicle objects."
print(result)
print(list_of_vehicles)
print(str(Car.numCars) + " of them are Cars")
print(str(Truck.numTrucks) + " of them are Trucks")
#Example output \ 
#There are 5 Vehicle objects ['Car', 'Car', 'Truck', 'Truck', 'Car'] 
#\ 3 of them are Cars \ 2 of them are Trucks \

There are 5 Vehicle objects.
['Car', 'Truck', 'Truck', 'Truck', 'Truck']
1 of them are Cars
4 of them are Trucks


#### This is the end of assignment 2